/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 * Generated by @nextspark/core
 * Regenerate with: npx nextspark generate
 */

import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import { NextIntlClientProvider } from 'next-intl'
import { getMessages } from 'next-intl/server'

import "./globals.css"
import { getBillingResourceHints } from "@nextsparkjs/core/lib/billing/gateways/factory"
import { ThemeProvider as NextThemeProvider } from "@nextsparkjs/core/providers/theme-provider"
import { ThemeProvider as CustomThemeProvider } from "@nextsparkjs/core/lib/theme/ThemeProvider"
import { getUserLocale } from '@nextsparkjs/core/lib/locale'
import { TranslationContextManager } from "@nextsparkjs/core/providers/TranslationContextManager"
import { PluginService } from '@nextsparkjs/core/lib/services'
import { getMetadataOrDefault } from '@nextsparkjs/core/lib/template-resolver'
import { getDefaultThemeMode } from '@nextsparkjs/core/lib/theme/get-default-theme-mode'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

const defaultMetadata: Metadata = {
  title: "NextSpark App",
  description: "Built with NextSpark",
}

export const metadata: Metadata = getMetadataOrDefault(
  'app/layout.tsx',
  defaultMetadata
)

let pluginsInitialized = false

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  if (!pluginsInitialized) {
    await PluginService.initializeAll()
    pluginsInitialized = true
  }

  const locale = await getUserLocale()
  const messages = await getMessages({ locale })
  const defaultTheme = await getDefaultThemeMode()

  return (
    <html lang={locale} suppressHydrationWarning>
      <head>
        {(() => {
          const hints = getBillingResourceHints()
          return (
            <>
              {hints.preconnect.map((domain) => (
                <link key={`pre-${domain}`} rel="preconnect" href={domain} />
              ))}
              {[...hints.preconnect, ...hints.dnsPrefetch].map((domain) => (
                <link key={`dns-${domain}`} rel="dns-prefetch" href={domain} />
              ))}
            </>
          )
        })()}
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextIntlClientProvider locale={locale} messages={messages}>
          <NextThemeProvider
            attribute="class"
            defaultTheme={defaultTheme}
            enableSystem
            disableTransitionOnChange
          >
            <CustomThemeProvider>
              <TranslationContextManager />
              <main>{children}</main>
            </CustomThemeProvider>
          </NextThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
